/**
 * ⚠️ DO NOT EDIT MANUALLY — auto-generated by deploy scripts
 * AI: KHÔNG được chỉnh sửa file này trực tiếp.
 * Thay vào đó, ghi vào .brain/session.json → recent_changes[]
 * Deploy script sẽ đọc và ghi changelog tự động.
 */
export interface ChangelogEntry {
  version: string;
  date: string; // YYYY-MM-DD
  changes: {
    type: "new" | "fix" | "ui" | "perf";
    text: string;
  }[];
}

export const CHANGELOG_EMOJI: Record<string, string> = {
  new: "✨",
  fix: "🐛",
  ui: "🎨",
  perf: "⚡",
};

export const changelog: ChangelogEntry[] = [
  {
    version: "2.0.0",
    date: "2026-04-01",
    changes: [
      { type: "new", text: "V2 Architecture — SSOT Design System, CSS Modular" },
      { type: "new", text: "Services Module V2 — Visual Builder, Quote Modal" },
      { type: "new", text: "Contracts Module V2 — Gold Standard compliance" },
      { type: "perf", text: "Radix UI primitives cho Select, Switch" },
      { type: "ui", text: "Lucide-react icons thay material-symbols" },
    ],
  },
];
