-- Remove legacy autogenerated staff-task placeholders.
-- work_tasks are staff assignments; unassigned zero-cost placeholders caused
-- contract detail/calendar progress to show tasks that no one could edit usefully.

BEGIN;

DELETE FROM public.work_tasks wt
USING public.contract_events ce
WHERE wt.event_id = ce.id
  AND wt.assigned_to IS NULL
  AND COALESCE(wt.cost, 0) = 0
  AND wt.notes IS NULL
  AND wt.start_time IS NULL
  AND wt.end_time IS NULL
  AND wt.completion_date IS NULL
  AND COALESCE(wt.status, 'chua_lam') IN ('chua_lam', 'da_huy');

COMMIT;
