-- Durable Moodie voice sessions and turn telemetry.
CREATE TABLE IF NOT EXISTS public.moodie_voice_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  conversation_id UUID REFERENCES public.ai_conversations(id) ON DELETE SET NULL,
  engine TEXT NOT NULL DEFAULT 'live' CHECK (engine IN ('live', 'cascade')),
  model TEXT NOT NULL,
  voice TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'issued' CHECK (status IN ('issued', 'connecting', 'connected', 'ended', 'failed')),
  policy_version INTEGER NOT NULL DEFAULT 1,
  memory_packet_version INTEGER NOT NULL DEFAULT 1,
  reconnect_count INTEGER NOT NULL DEFAULT 0 CHECK (reconnect_count >= 0),
  client_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_event_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  connected_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.moodie_voice_turns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES public.moodie_voice_sessions(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sequence INTEGER NOT NULL CHECK (sequence > 0),
  user_transcript TEXT,
  assistant_transcript TEXT,
  first_input_at TIMESTAMPTZ,
  first_input_transcript_at TIMESTAMPTZ,
  first_assistant_audio_at TIMESTAMPTZ,
  playback_started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  interrupted BOOLEAN NOT NULL DEFAULT false,
  delegated_run_ids UUID[] NOT NULL DEFAULT '{}',
  metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(session_id, sequence)
);

CREATE TABLE IF NOT EXISTS public.moodie_voice_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID NOT NULL REFERENCES public.moodie_voice_sessions(id) ON DELETE CASCADE,
  turn_id UUID REFERENCES public.moodie_voice_turns(id) ON DELETE SET NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  sequence INTEGER NOT NULL CHECK (sequence > 0),
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(session_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_moodie_voice_sessions_user_recent
  ON public.moodie_voice_sessions(user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_moodie_voice_turns_session_sequence
  ON public.moodie_voice_turns(session_id, sequence);
CREATE INDEX IF NOT EXISTS idx_moodie_voice_events_session_sequence
  ON public.moodie_voice_events(session_id, sequence);

ALTER TABLE public.moodie_voice_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.moodie_voice_turns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.moodie_voice_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage own Moodie voice sessions" ON public.moodie_voice_sessions;
CREATE POLICY "Users manage own Moodie voice sessions"
  ON public.moodie_voice_sessions FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users manage own Moodie voice turns" ON public.moodie_voice_turns;
CREATE POLICY "Users manage own Moodie voice turns"
  ON public.moodie_voice_turns FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users manage own Moodie voice events" ON public.moodie_voice_events;
CREATE POLICY "Users manage own Moodie voice events"
  ON public.moodie_voice_events FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

COMMENT ON TABLE public.moodie_voice_sessions IS 'Durable metadata for Moodie realtime and cascade voice sessions. Raw audio is not stored.';
COMMENT ON TABLE public.moodie_voice_turns IS 'Per-turn transcripts and latency checkpoints for Moodie voice.';
COMMENT ON TABLE public.moodie_voice_events IS 'Sanitized voice lifecycle events used to prove end-to-end audio behavior.';
