-- Durable background runs and explicit confirmation evidence for Moodie.
CREATE TABLE IF NOT EXISTS public.moodie_agent_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  conversation_id UUID REFERENCES public.ai_conversations(id) ON DELETE SET NULL,
  voice_session_id UUID REFERENCES public.moodie_voice_sessions(id) ON DELETE SET NULL,
  parent_turn_id UUID REFERENCES public.ai_turns(id) ON DELETE SET NULL,
  kind TEXT NOT NULL CHECK (kind IN ('task', 'research', 'action')),
  title TEXT NOT NULL,
  request JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'proposed' CHECK (status IN (
    'proposed', 'awaiting_confirmation', 'queued', 'running',
    'completed', 'failed', 'cancelled', 'expired'
  )),
  requires_confirmation BOOLEAN NOT NULL DEFAULT false,
  confirmation_token_hash TEXT,
  confirmation_expires_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  confirmed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  progress INTEGER NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  result JSONB,
  error TEXT,
  source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  idempotency_key TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.moodie_agent_run_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id UUID NOT NULL REFERENCES public.moodie_agent_runs(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sequence INTEGER NOT NULL CHECK (sequence > 0),
  event_type TEXT NOT NULL,
  message TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, sequence)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_moodie_agent_runs_user_idempotency
  ON public.moodie_agent_runs(user_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_moodie_agent_runs_user_recent
  ON public.moodie_agent_runs(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_moodie_agent_runs_status
  ON public.moodie_agent_runs(status, updated_at);
CREATE INDEX IF NOT EXISTS idx_moodie_agent_run_events_run_sequence
  ON public.moodie_agent_run_events(run_id, sequence);

ALTER TABLE public.moodie_agent_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.moodie_agent_run_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage own Moodie agent runs" ON public.moodie_agent_runs;
CREATE POLICY "Users manage own Moodie agent runs"
  ON public.moodie_agent_runs FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users manage own Moodie agent run events" ON public.moodie_agent_run_events;
CREATE POLICY "Users manage own Moodie agent run events"
  ON public.moodie_agent_run_events FOR ALL TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

COMMENT ON TABLE public.moodie_agent_runs IS
  'Durable Moodie background tasks, research jobs, and consequential actions.';
COMMENT ON TABLE public.moodie_agent_run_events IS
  'Ordered progress and terminal events for Moodie agent runs.';
